baseURL = "https://bhushan.codes/"
languageCode = "en-us"
title = "Bhushan Khanale"
googleAnalytics = "UA-165070744-1"

[params]
    author = "Bhushan Khanale"
    description = "Developer + Competitive Programmer"
    githubUsername = "bkhanale"
    accent = "teal"
    showBorder = false
    font = "Roboto Mono"
    highlightLanguages = ["go", "julia"]
    js = ["js/dark-switch.js",]

[markup]
  [markup.highlight]
    style = "solarized-dark"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:bkhanale@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/bkhanale/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/BhushanKhanale/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/bhushan-khanale/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://github.com/bkhanale/resume/raw/master/bhushan_resume.pdf"
    name = "file-pdf-o"
    weight = 5
